config/routes.rb
Rails.application.routes.draw do

  # 会員用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲストユーザーをログイン状態にする
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/customers/sessions#guest_sign_in'
    get 'customers', to: 'public/registrations#index'
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    resources :items, only: [:index, :show]
      resource :customers,only: [] do
      get "my_page"=>"customers#show"
      get "information/edit"=>"customers#edit"
      patch "information"=>"customers#update"
      get "quit"
      patch "out"
    end
      resources :cart_items, only: [:index, :create, :update, :destroy] do
        collection do
          delete "all_destroy"
      end
    end
    resources :pre_orders, only: [:new, :index, :show, :create, :destroy] do
      collection do
        post "check"
        get "over"
      end
    end
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    get "pre_orders" => "homes#top"
    resources :pre_orders, only: [:show]
    resources :pre_order_details, only: [:update]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  
  # through:「多対多」のつながりを設定
  belongs_to :genre
  has_many :cart_items
  has_many :pre_orders, through: :pre_order_details
  has_many :pre_order_details

  validates :genre_id, :name, :introduction, :calorie, :allergy, :price, :is_active, presence: true
  
  # has_one_attached :レコードとファイルの間に1対1のマッピングを設定。レコード1件ごとに1個の画像を添付できる。
  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  # with_tax_price: 消費税を求めるメソッド、round： 小数点切り上げ
  def with_tax_price
    (self.price * 1.10).round
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  before_action :authenticate_admin!
  # メニュー一覧、order(created_at: :desc)：最新のメニューを1ページ目に表示
  def index
    @items = Item.order(created_at: :desc).page(params[:page]).per(5)
  end
  # メニュー新規登録画面
  def new
    @item = Item.new
    @genres = Genre.all
  end
  # メニュー情報の新規登録
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "メニューが保存されました。"
      redirect_to admin_item_path(@item.id)
    else
      flash[:alert] = "正しい情報を入力してください。"
      @genres = Genre.all
      render :new
    end
  end
  # メニュー詳細
  def show
    @item = Item.find(params[:id])
  end
  # メニュー編集
  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end
  # メニュー更新
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id), notice: "メニューを更新しました。"
    else
      flash[:alert] = "メニューを更新に失敗しました。"
      @genres = Genre.all
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :calorie, :allergy, :price, :is_active, :image)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<h2 class="head-line title_h2 text-center"><b>メニュー編集</b></h2>
<div class="row">
  <div class="col-ms-12 mx-auto p-5">
    <%= form_for(@item, url: admin_item_path, method: :patch, class: "form-horizontal") do |f| %>
      <div class="form-group col-12 p-2">
        <%= f.label :"メニュー画像", class: "col-3 control-label" %>
        <%= f.file_field :image, accept: "image/*", class: "image col-8" %>
      </div>
    
      <div class="form-group col-12 p-2">
        <%= f.label :"メニュー名", class: "col-3 control-label" %>
        <%= f.text_field :name, class: "col-8" %>
      </div>
    
      <div class="form-group col-12 p-2">
        <%= f.label :"メニューの説明", class: "col-3 control-label" %>
        <%= f.text_area :introduction, class: "col-8" %>
      </div>
    
      <div class="form-group col-12 p-2">
        <%= f.label :"カロリー", class: "col-3 control-label" %>
        <%= f.text_field :calorie, class: "col-8" %> kcal
      </div>
    
      <div class="form-group col-12 p-2">
        <%= f.label :"アレルギー物質", class: "col-3 control-label" %>
        <%= f.text_field :allergy, class: "col-8" %>
      </div>
    
      <div class="form-group col-12 p-2">
        <%= f.label :"ジャンル", class: "col-3 control-label" %>
        <%= f.collection_select(:genre_id, @genres, :id, :name, prompt: "-- 選択してください --", class: "col-8") %>
      </div>
    
      <div class="form-group col-12 p-2">
        <%= f.label :"税抜価格", class: "col-3 control-label" %>
        <%= f.text_field :price, class: "col-8" %> 円
      </div>
    
      <div class="form-group col-12 p-2">
        <%= f.label :"販売ステータス", class: "col-4 control-label" %>
        <%= f.radio_button :is_active, "true" %>
        <%= f.label :"販売中", class: "col-3" %>
        <%= f.radio_button :is_active, "false" %>
        <%= f.label :"販売停止", class: "col-3" %>
      </div>
    
      <div class="actions text-center p-3">
        <%= f.submit "変更を保存", class: "btn btn-success btn-lg pull-right col-4" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<h2 class="head-line title_h2 text-center admin_product_index"><b>メニュー</b></h2>
<div class="row">
  <div class="col-8 text-center mx-auto p-5">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>メニューID</th>
          <th>メニュー名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>販売ステータス</th>
        </tr>
      </thead>
      <tbody>
				<% @items.each do |item| %>
  				<tr>
            <td class="auto">
              <%= item.id %>
            </td>
            <td class="auto">
              <%= link_to admin_item_path(item), class: "btn-link" do %>
                <%= item.name %>
              <% end %>
            </td>
            <td class="auto">
              <!--delimited数値を3桁区切りにする-->
              ¥<%= item.price.to_s(:delimited) %>
            </td>
            <td class="auto">
              <%= item.genre.name %>
            </td>
            <td class="auto">
              <% if item.is_active == true %>
      					<p>販売中</p>
      				<% elsif item.is_active == false %>
      					<p>販売停止中</p>
      				<% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div>
      <%= link_to new_admin_item_path, class: "btn btn-info pull-right new_product float-right p-3 m-4" do %>
        メニューの新規登録 <i class="fas fa-plus"></i>
      <% end %>
    </div>
    <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container my-5 px-5 px-sm-0">
  <div class="row">
    <div class="col-sm-12">
      <div class="px-5 py-4">
        <h3>メニュー新規登録</h3>
      </div>
      <div class="col-11 offset-1">
        <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
          <div class="form-group row">
            <%= f.label :"メニュー画像", class: "col-3 control-label" %>
    	      <%= f.file_field :image, accept: "image/*", class: "image col-8" %>
    	    </div>
    
          <div class="form-group row">
            <%= f.label :"メニュー名", class: "col-3 control-label" %>
            <%= f.text_field :name, class: "col-8" %>
          </div>
    
          <div class="form-group row">
            <%= f.label :"メニューの説明", class: "col-3 control-label" %>
            <%= f.text_area :introduction, class: "col-8" %>
          </div>
    
          <div class="form-group row">
            <%= f.label :"カロリー", class: "col-3 control-label" %>
            <%= f.text_field :calorie, class: "col-8" %>kcal
          </div>
    
          <div class="form-group row">
            <%= f.label :"アレルギー物質", class: "col-3 control-label" %>
            <%= f.text_field :allergy, class: "col-8" %>
          </div>
    
          <div class="form-group row">
            <%= f.label :"ジャンル", class: "col-3 control-label" %>
            <%= f.collection_select(:genre_id, @genres, :id, :name, prompt: "-- 選択してください --", class: "col-8") %>
          </div>
    
          <div class="form-group row">
            <%= f.label :"税抜価格", class: "col-3 control-label" %>
            <%= f.text_field :price, class: "col-8" %>円
          </div>
    
          <div class="form-group row">
            <%= f.label :"販売ステータス", class: "col-md-3 font-weight-bold" %>
            <p class="col-2"><%= f.radio_button :is_active, "true" %>販売中</p>
            <p class="col-2"><%= f.radio_button :is_active, "false" %>販売停止中</p>
          </div>
    
          <div class="form-group col-2 offset-3 mt-2">
            <%= f.submit "新規登録", class: 'btn btn-success btn-lg' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<h2 class="head-line title_h2 text-center m-5">メニュー詳細</h2>
<div class="row">
	<div class="col-6 text-right pr-5">
    <div id="img_fiel">
  	  <%= image_tag @item.get_image(300,300) %>
    </div>
  </div>
  <div class="col-6">
    <div class="field">
	    <p>メニュー名 :
	    <%= @item.name %></p>
    </div><br>

    <div class="field">
	    <p>メニューの説明 :
	    <%= @item.introduction %></p><br>
    </div>

    <div class="field">
	    <p>カロリー :
	    <%= @item.calorie %> kcal</p><br>
    </div>

    <div class="field">
	    <p>アレルギー物質 :
	    <%= @item.allergy %></p><br>
    </div>

    <div class="field">
	    <p>ジャンル :
	    <%= @item.genre.name %></p><br>
    </div>

    <div class="field">
	    <p>税込価格 :
	    <%= @item.with_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>) 円<br>
	      (税抜価格)
	    </p><br>
    </div>
    <div class="field">

		<div class="field">
		  <p>販売ステータス :
	      <% if @item.is_active == true %>
	        <b class="text-success">　販売中</b>
  		  <% elsif @item.is_active == false %>
  			  <b class="text-success">　販売停止中</b>
  		  <% end %>
		  </p>
		</div>
  </div>
    <div class="actions">
      <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success col-3 m-4 p-3" %>
    </div>
  </div>
</div>