config/routes.rb
Rails.application.routes.draw do

  # 会員用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲストユーザーをログイン状態にする
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/customers/sessions#guest_sign_in'
    get 'customers', to: 'public/registrations#index'
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    resources :items, only: [:index, :show]
      resource :customers,only: [] do
      get "my_page"=>"customers#show"
      get "information/edit"=>"customers#edit"
      patch "information"=>"customers#update"
      get "quit"
      patch "out"
    end
      resources :cart_items, only: [:index, :create, :update, :destroy] do
        collection do
          delete "all_destroy"
      end
    end
    resources :pre_orders, only: [:new, :index, :show, :create, :destroy] do
      collection do
        post "check"
        get "over"
      end
    end
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    get "pre_orders" => "homes#top"
    resources :pre_orders, only: [:show]
    resources :pre_order_details, only: [:update]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # dependent: :destroy =>「親モデルを削除する際に、その親モデルに紐づく「子モデル」も一緒に削除できる」
  has_many :pre_orders, dependent: :destroy
  has_many :cart_items
  
   # numericality: {only_integer: true}=>整数のみ許可、length: { in: 10..11 }=>文字数制限(10〜11桁)
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :tel_number, presence: true
  
  # update_without_current_password：パスワード抜きで更新できるようにするメソッド
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    # params[:password]に紐づく要素が存在しなかった場合は、: passwordと:password_confirmationをキーに持つ要素を取り除く
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
    
    # update_attributes: Hashを引数に渡してデータベースのレコードを複数同時に更新することができるメソッド
    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
  # そのモデルのis_deletedカラムがfalseを返す（= 削除された会員でない）と、このメソッドはtrueと評価され、ログインすることができる。
  def active_for_authentication?
    super && (is_deleted == false)
  end

  #find_or_create_by:データの検索と作成を自動的に判断して処理を行う、Railsのメソッド
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.last_name = 'guestcustomer'
      customer.first_name = 'guestcustomer'
      customer.last_name_kana = 'guestcustomer'
      customer.first_name_kana = 'guestcustomer'
      customer.tel_number = 'guestcustomer'
    end
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!
  # 会員一覧
  def index
    @customers = Customer.page(params[:page]).per(10)
  end
  # 会員詳細
  def show
    @customer = Customer.find(params[:id])
  end
  # 会員編集
  def edit
    @customer = Customer.find(params[:id])
  end
  # 会員情報の更新
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer), notice: "会員情報を編集しました。"
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :tel_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 mx-auto">
      <div class="text-center p-4">
        <h2><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h2>
      </div>
      
      <%= form_with(model: @customer, url:admin_customer_path, local: true , method: :patch) do |f| %>
        <div class="field form-group col-12">
          <%= f.label :"名前", class: "col-2 control-label" %>
          <%= f.label :"（姓）　", class: "control-label ml-5 mr-2" %>
          <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "col-3" %>
          <%= f.label :"（名）　", class: "control-label pl-4" %>
          <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: "col-3" %>
        </div>
        
        <div class="field form-group col-12">
          <%= f.label :"フリガナ", class: "col-2 control-label" %>
          <%= f.label :"（セイ）", class: "control-label ml-5 mr-2" %>
          <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana", class: "col-3" %>
          <%= f.label :"（メイ）", class: "control-label pl-4" %>
          <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana", class: "col-3" %>
        </div>
        
        <div class="field form-group col-12">
          <%= f.label :"電話番号(ハイフンなし)", class: "col-4 control-label" %>
          <%= f.text_field :tel_number, autofocus: true, autocomplete: "tel_number", class: "col-3" %>
        </div>
        
        <div class="field form-group col-12">
          <%= f.label :"メールアドレス", class: "col-3 control-label mr-3" %>
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "col-3 ml-5" %>
        </div>
        
        <div class="field form-group col-12">
          <%= f.label :"会員ステータス", class: "col-sm-6 control-label" %>
          <%= f.radio_button :is_deleted, "false" %>
          <%= f.label :"有効" %>
          <%= f.radio_button :is_deleted, "true" %>
          <%= f.label :"退会" %>
        </div>
        
        <div class="actions text-center p-3">
          <%= f.submit "編集内容を保存", class: "btn btn-success col-3 mr-5" %>
        </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <div class="row my-4">
        <div class="col-6">
          <h3 class="">会員一覧</h3>
        </div>
        
          <table class="table table-hover">
            <thead>
              <tr>
                <th>会員ID</th>
                <th>氏名</th>
                <th>メールアドレス</th>
                <th>会員ステータス</th>
              </tr>
            </thead>
            <tbody>
            	<% @customers.each do |customer| %>
              	<tr>
                  <td><%= customer.id %></td>
                  <td><%= link_to admin_customer_path(customer.id) do %>
                      <%= customer.last_name + customer.first_name %>
                      <% end %>
                  </td>
                  <td><%= customer.email %></td>
                  <td>
                    <!--is_deleted:削除されていますか-->
                    <% if customer.is_deleted == false %>
                      <p>有効</p>
                     <% elsif customer.is_deleted == true %>
                      <p>退会</p>
                  	<% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
    
          <%= paginate @customers %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <div class="row my-4">
        <div class="col-6">
          <h3 class="">
            <%= @customer.last_name + @customer.first_name %>さんの会員詳細
          </h3>
        </div>
        <table class="table table-borderless">
          <tr>
            <th>会員ID</th>
            <th><%= @customer.id %></th>
          </tr>
          <tr>
            <th>氏名</th>
            <th><%= @customer.last_name + @customer.first_name %></th>
          </tr>
          <tr>
            <th>フリガナ</th>
            <th><%= @customer.last_name_kana + @customer.first_name_kana %></th>
          </tr>
            <th>電話番号</th>
            <th><%= @customer.tel_number %></th>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <th><%= @customer.email %></th>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <th>
              <% if @customer.is_deleted == false %>
        	      <b class="text-success">　有効</b>
        		  <% elsif @customer.is_deleted == true %>
        			  <b class="text-success">　退会</b>
        		  <% end %>
            </th>
          </tr>
          <tr>
            <th></th>
            <th><%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success ml-4" %></th>
            <th><%= link_to "予約注文履歴一覧を見る", admin_pre_orders_path, class:"btn btn-info ml-4" %></th>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>