config/routes.rb
Rails.application.routes.draw do

  # 会員用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲストユーザーをログイン状態にする
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/customers/sessions#guest_sign_in'
    get 'customers', to: 'public/registrations#index'
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    resources :items, only: [:index, :show]
      resource :customers,only: [] do
      get "my_page"=>"customers#show"
      get "information/edit"=>"customers#edit"
      patch "information"=>"customers#update"
      get "quit"
      patch "out"
    end
      resources :cart_items, only: [:index, :create, :update, :destroy] do
        collection do
          delete "all_destroy"
      end
    end
    resources :pre_orders, only: [:new, :index, :show, :create, :destroy] do
      collection do
        post "check"
        get "over"
      end
    end
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    get "pre_orders" => "homes#top"
    resources :pre_orders, only: [:show]
    resources :pre_order_details, only: [:update]
  end
end

app/models/pre_order.rb
class PreOrder < ApplicationRecord
  # 10時から20時の間で受け取り時間を選択
  START_HOUR = 10
  END_HOUR = 20

  belongs_to :customer
  # 予約注文がキャンセルされたら予約注文詳細も削除する
  has_many :pre_order_details, dependent: :destroy
  has_many :items, through: :pre_orders_details
  
  # 小計を求めるメソッド
  def subtotal
    item.with_tax_price * quantity
  end
  
  # 受取り日と受取り時間のバリデーション
  validates :receiving_date, presence: true
  validates :receiving_time, presence: true
  
  validate :expiration_date_cannot_be_in_the_past
  validate :over_time
  
  def expiration_date_cannot_be_in_the_past
      receiving_date_time= Time.zone.parse(
      "#{receiving_date.to_s} #{receiving_time.hour}:#{receiving_time.min}"
      ) 
    return if receiving_date_time >= Time.current

    errors.add(:base, "受取日、または受け取り時間の変更を行なってください。")
  end
  
  def over_time
    return if receiving_time.hour >= START_HOUR && receiving_time.hour <= END_HOUR
    
    errors.add(:base, "営業時間内の時間を指定してください。")
  end

end

app/controllers/admin/pre_orders_controller.rb
class Admin::PreOrdersController < ApplicationController

  before_action :authenticate_admin!
  # 予約注文詳細
  def show
    @pre_order_details = PreOrderDetail.where(pre_order_id: params[:id])
    @pre_order = PreOrder.find(params[:id])
    @total_payment = calculate(@pre_order)
  end

  def calculate(total_payment)
    @total_paymen = 0
    @pre_order_details.each {|pre_order_detail|
    subtotal = pre_order_detail.tax_price * pre_order_detail.quantity
    @total_paymen += subtotal
    }
    return @total_paymen
  end

end

app/helpers/admin/pre_orders_helper.rb
module Admin::PreOrdersHelper
end

app/views/admin/pre_orders/show.html.erb
<div class="containar">
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <h3>予約注文履歴詳細</h3><br>
      <table class="table table-borderless table-sm">  
        <%= form_with model: @pre_order, url: admin_pre_order_path do |f| %>
          <tr>
            <td>購入者</td>
            <td>
              <%= link_to admin_customer_path(@pre_order.customer_id) do %>
                <%= @pre_order.customer.last_name + @pre_order.customer.first_name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td>予約注文日</td>
            <td><%= @pre_order.created_at.strftime('%Y年%m月%d日') %></td>
          </tr>
          <tr>
            <td>受取り日</td>
            <td><%= @pre_order.receiving_date.strftime('%m月%d日') %></td>
          </tr>
          <tr>
            <td>受取り時間</td>
            <td><%= @pre_order.receiving_time.strftime("%H時%M分") %></td>
          </tr>
          <tr>
            <td>ご要望</td>
            <td><%= @pre_order.demand %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  
  <div class="row justify-content-center">
    <div class="col-lg-7 mt-3">
      <table class="table table-bordered border-dark">
        <tr class="table-secondary">
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>
        <% @pre_order_details.each do |pre_order_detail| %>
          <tr>
            <td><%= pre_order_detail.item.name %></td>
            <td><%= pre_order_detail.tax_price %></td>
            <td><%= pre_order_detail.quantity %></td>
            <td><%= pre_order_detail.quantity.to_i * pre_order_detail.tax_price %>円</td>
            <td>
              <%= form_with model: pre_order_detail, url: admin_pre_order_detail_path(pre_order_detail.id), method: :patch do |f| %>
                <%= f.label :"製作ステータス", class: "col-sm-6 control-label" %>
                <%= f.radio_button :is_maked, "false" %>
                <%= f.label :"製作中" %>
                <%= f.radio_button :is_maked, "true" %>
                <%= f.label :"製作完了" %>
                <%= f.submit "更新", class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="col-lg-3 mt-3">
      <table class="table table-borderless">
        <tr>
          <th>請求金額</th>
          <td><strong><%= @total_payment %> 円</strong></td>
        </tr>
      </table>
    </div>
  </div>
</div>