config/routes.rb
Rails.application.routes.draw do

  # 会員用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲストユーザーをログイン状態にする
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/customers/sessions#guest_sign_in'
    get 'customers', to: 'public/registrations#index'
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    resources :items, only: [:index, :show]
      resource :customers,only: [] do
      get "my_page"=>"customers#show"
      get "information/edit"=>"customers#edit"
      patch "information"=>"customers#update"
      get "quit"
      patch "out"
    end
      resources :cart_items, only: [:index, :create, :update, :destroy] do
        collection do
          delete "all_destroy"
      end
    end
    resources :pre_orders, only: [:new, :index, :show, :create, :destroy] do
      collection do
        post "check"
        get "over"
      end
    end
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    get "pre_orders" => "homes#top"
    resources :pre_orders, only: [:show]
    resources :pre_order_details, only: [:update]
  end
end

app/views/layouts/_header.html.erb
<header class="shadow sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#FFF">
    <div class="container">
      <a class="navbar-brand font-weight-normal" href="/"><%= image_tag 'logo.jpg', size: "100x100"%></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="text-left">
        <p>※架空のお弁当屋さん「Mogu」の<br>予約注文サイト</p>
        <div class="text-info">
          <% if customer_signed_in? && current_customer.email == 'guest@example.com' %>
            <h5>ようこそ、ゲストさん！</h5>
          <% elsif customer_signed_in? %>
            <h5>ようこそ、<%= current_customer.first_name %>さん！</h5>
          <% end %>
        </div>
      </div>

      <div class="navbar">
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <!--ゲストログインかどうかの確認-->
            <% if customer_signed_in? && current_customer.email == 'guest@example.com' %>
              <li>
                <%= link_to about_path,class: 'btn btn-dark rounded-pill' do %>
                <i class="fas fa-apple-alt"></i>About
                <% end %>
              </li>
              <li>
                <%= link_to items_path,class: 'btn btn-dark rounded-pill' do %>
                <i class="fas fa-book-open"></i> メニュー
                <% end %>
              </li>
              <li>
                <%= link_to destroy_customer_session_path, method: :delete,class: 'btn btn-dark rounded-pill' do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
                <% end %>
              </li>
            <!--会員ログイン-->
            <% elsif customer_signed_in? %>
              <li>
                <%= link_to my_page_customers_path,class: 'btn btn-dark rounded-pill' do %>
                <i class="fas fa-user"></i> マイページ
                <% end %>
              </li>
              <li>
                <%= link_to pre_orders_path,class: 'btn btn-dark rounded-pill' do %>
                <i class="fas fa-star"></i> 予約注文履歴一覧
                <% end %>
              </li>
              <li>
                <%= link_to items_path,class: 'btn btn-dark rounded-pill' do %>
                <i class="fas fa-book-open"></i> メニュー
                <% end %>
              </li>
              <li>
                <%= link_to cart_items_path ,class: 'btn btn-dark rounded-pill' do %>
                <i class="fas fa-shopping-cart"></i>カート
                <% end %>
              </li>
              <li>
                <%= link_to destroy_customer_session_path, method: :delete,class: 'btn btn-dark rounded-pill' do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
                <% end %>
              </li>
            <!--管理者ログイン-->
            <% elsif admin_signed_in? %>
              <li><%= link_to admin_items_path,class: 'btn btn-dark rounded-pill' do %> メニュー <% end %></li>
              <li><%= link_to admin_customers_path,class: 'btn btn-dark rounded-pill' do %> 会員一覧 <% end %></li>
              <li><%= link_to admin_pre_orders_path,class: 'btn btn-dark rounded-pill' do %> 予約注文履歴一覧 <% end %> </li>
              <li><%= link_to admin_genres_path,class: 'btn btn-dark rounded-pill' do %> ジャンル  <% end %></li>
              <li><%= link_to destroy_admin_session_path, method: :delete,class: 'btn btn-dark rounded-pill' do %> ログアウト <% end %></li>
            <% else %>
              <li>
                <%= link_to 'ゲストログイン（閲覧用）', customers_guest_sign_in_path, class: "btn btn-dark rounded-pill sign_in", method: :post %>
              </li>
              <li>
                <%= link_to about_path,class: 'btn btn-dark rounded-pill' do %>
                <i class="fas fa-apple-alt"></i>About
                <% end %>
              </li>
              <li>
                <%= link_to items_path,class: 'btn btn-dark rounded-pill' do %>
                <i class="fas fa-book-open"></i> メニュー
                <% end %>
              </li>
              <li>
                <%= link_to new_customer_registration_path,class: 'btn btn-dark rounded-pill' do %>
                <i class="fas fa-user-plus"></i> 新規登録
                <% end %>
              </li>
              <li>
                <%= link_to new_customer_session_path ,class: 'btn btn-dark rounded-pill' do %>
                <i class="fas fa-sign-in-alt"></i> ログイン
                <% end %>
              </li>

            <% end %>
          </ul>
        </div>
        <div class="container-fluid">
          <a class="navbar-brand"></a>
        </div>
      </div>

    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoguBento</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.pay.jp/" , type="text/javascript"></script>
    <!--Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic&display=swap" rel="stylesheet">
  </head>
  
  <body style="background-color:#bcc7d7;">
    <div class="pb-5 sticky-top"><%= render 'layouts/header' %></div>
    <main>
      <% if flash[:notice] %>
        <div class="alert alert-light">
          <span class="ml-2"><%= notice %></span>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-light">
          <span class="ml-2"><%= alert %></span>
        </div>
      <% end %>
    </main>
    <div class="mb-5"><%= yield %></div>
  </body>
</html>